default_stages: [commit, push]
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        exclude: ^(submodules/)
      - id: check-merge-conflict
        exclude: ^(submodules/)
      - id: check-vcs-permalinks
        exclude: ^(submodules/)
      - id: check-yaml
        exclude: ^(submodules/|terraform/|apps\/template.yaml)
        args: ['--unsafe']
      - id: detect-private-key
        exclude: ^(submodules/)
      - id: end-of-file-fixer
        exclude: ^(submodules/)
      - id: trailing-whitespace
        exclude: ^(submodules/)
      - id: check-ast
        exclude: ^(submodules/)

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      exclude: ^(submodules/)
      args: ["--config=./.flake8"]
      additional_dependencies: [
          Flake8-pyproject,
          flake8,
          flake8-blind-except, # A flake8 extension that checks for blind except: statements
          flake8-bugbear, # A plugin for flake8 finding likely bugs and design problems in your program.
          flake8-builtins, # Check for python builtins being used as variables or parameters.
          flake8-comprehensions, # It helps you write better list/set/dict comprehensions.
          flake8-deprecated, # Warns about deprecated method calls.
          flake8-eradicate, # Flake8 plugin to find commented out code
          flake8-variables-names, # flake8 extension that helps to make more readable variables names
          # flake8-tabs, # Tab (or Spaces) indentation style checker for flake8
          pep8-naming, # Check PEP-8 naming conventions, plugin for flake8
      ]
      types: [python]
      require_serial: true

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      exclude: ^(submodules/)
      name: isort (python)
      args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      exclude: ^(submodules/)
      name: black
      entry: black
      types: [python]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
        args: ['--exclude-files', '.*\.ipynb$', '--exclude-lines', '"(hash|id|image/\w+)"']
        exclude: ^.*\/(tests)\/(events)\/(submodules)\/.*\.json$
